config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :drivers
  resources :riders
  get 'users/new'

  get 'users/edit'

  get 'users/index'

  get 'users/show'

  root 'pages#home'

  get 'onboard' => 'pages#onboard'
  get 'req' => 'pages#req'

  get 'signin' => 'users#new'
  get 'ride' => 'riders#new'
  get 'drive'=> 'drivers#new'

  get 'pages/home'

  get 'pages/about'

  get 'pages/help'

  get 'pages/support'

end

app/models/driver.rb
class Driver < ActiveRecord::Base
end

app/models/ins_company.rb
class InsCompany < ActiveRecord::Base
end

app/models/rider.rb
class Rider < ActiveRecord::Base
  has_attached_file :ins_card_photo,
                   styles: { normal: '180x180#', thumb: '32x32#', medium: '64x64#' }
  validates_attachment_content_type :ins_card_photo, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  # GET /drivers
  # GET /drivers.json
  def index
    @drivers = Driver.all
  end

  # GET /drivers/1
  # GET /drivers/1.json
  def show
  end

  # GET /drivers/new
  def new
    @driver = Driver.new
  end

  # GET /drivers/1/edit
  def edit
  end

  # POST /drivers
  # POST /drivers.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to @driver, notice: 'Driver was successfully created.' }
        format.json { render :show, status: :created, location: @driver }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drivers/1
  # PATCH/PUT /drivers/1.json
  def update
    respond_to do |format|
      if @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:first_name, :last_name, :email, :password_digest, :license_no)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  require 'curb'
  require 'json'

  def home
  end

  def about
  end

  def help
  end

  def support
  end

  def onboard

  end

  def req
    c = Curl::Easy.new('https://api.coord.co/v1/ride/system/uber/product?longitude=-73.990773&latitude=40.745844&access_key=pVf-tBnK6qy141e4ScSBVA7ZKZ9G98DzH-Hd9oyCkVo')
    c.perform
    puts c.body_str
    @rides = JSON.parse(c.body_str)
  end
end

app/controllers/riders_controller.rb
class RidersController < ApplicationController
  require 'curb'
  require 'json'
  before_action :set_rider, only: [:show, :edit, :update, :destroy]

  # GET /riders
  # GET /riders.json
  def index
    @riders = Rider.all
  end

  # GET /riders/1
  # GET /riders/1.json
  def show
  end

  # GET /riders/new
  def new
    @rider = Rider.new
  end

  # GET /riders/1/edit
  def edit
  end

  # POST /riders
  # POST /riders.json
  def create
    @rider = Rider.new(rider_params)

if @rider.save
  http = Curl.post("https://api.coord.co/v1/users/testing/user_and_jwt?access_key=pVf-tBnK6qy141e4ScSBVA7ZKZ9G98DzH-Hd9oyCkVo", rider_params[:email]) do |x|
    x.headers['Content-Type'] = 'application/json'
    x.headers['Accept']       = 'application/json'
  end
  p "HERE"
  p rider_params[:email]
  response = JSON.parse(http.body_str)
  p response
  @rider.jwt_token = response['jwt_token']
  @rider.save # again?
  p 'COORD account created'
  redirect_to @rider
else
  render 'new'
end

    # respond_to do |format|
    #   if @rider.save
    #     # create COORD user
    #     # c.http_post(Curl::PostField.content('user[email]', "#{@rider.email}"))
    #
    #     # attach COORD acct
    #     format.html { redirect_to @rider, notice: 'Rider was successfully created.' }
    #     format.json { render :show, status: :created, location: @rider }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @rider.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # PATCH/PUT /riders/1
  # PATCH/PUT /riders/1.json
  def update
    respond_to do |format|
      if @rider.update(rider_params)
        format.html { redirect_to @rider, notice: 'Rider was successfully updated.' }
        format.json { render :show, status: :ok, location: @rider }
      else
        format.html { render :edit }
        format.json { render json: @rider.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /riders/1
  # DELETE /riders/1.json
  def destroy
    @rider.destroy
    respond_to do |format|
      format.html { redirect_to riders_url, notice: 'Rider was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rider
      @rider = Rider.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rider_params
      params.require(:rider).permit(:first_name, :ins_card_photo, :last_name, :phone, :email, :ins_provider_id, :tos_agreed, :provider)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to onboard_path, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password_digest, :phone)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/riders_helper.rb
module RidersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password_digest %><br>
    <%= f.password_field :password_digest %>
  </div>
  <div class="field">
    <%= f.label :license_no %><br>
    <%= f.text_field :license_no %>
  </div>
  <div class="actions">
    <%= f.submit 'Create Driver Account' %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing Driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Drivers</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>License no</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @drivers.each do |driver| %>
      <tr>
        <td><%= driver.first_name %></td>
        <td><%= driver.last_name %></td>
        <td><%= driver.email %></td>
        <td><%= driver.password_digest %></td>
        <td><%= driver.license_no %></td>
        <td><%= link_to 'Show', driver %></td>
        <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
        <td><%= link_to 'Destroy', driver, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Driver', new_driver_path %>

app/views/drivers/new.html.erb
<%= link_to 'Back', root_path %><br><br>
<h1>Drive with Purpose on Servo.</h1>

<%= render 'form' %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @driver.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @driver.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @driver.email %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @driver.password_digest %>
</p>

<p>
  <strong>License no:</strong>
  <%= @driver.license_no %>
</p>

<%= link_to 'Edit', edit_driver_path(@driver) %> |
<%= link_to 'Back', drivers_path %>

app/views/layouts/_top_logo.html.erb
<div class="title">
  <a href="/"><%= image_tag('/images/logo.png') %></a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Servo - The NEMT App for NYC</title>
  <link rel="stylesheet" href="https://cdn.rawgit.com/tonystar/float-label-css/v1.0.2/dist/float-label.min.css"/>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/help.html.erb
<h1>Pages#help</h1>
<p>Find me in app/views/pages/help.html.erb</p>

app/views/pages/home.html.erb
<%= render 'layouts/top_logo' %>
<h2 class="home-title">Welcome to Servo!</h2>
<p class="main-subtext">Non emergency medical transportation that's quick, reliable, and convenient.</p>
<div class="subsection">
  <%= link_to "Sign in", signin_path, class: 'btn btn-main' %>
</div>

app/views/pages/onboard.html.erb
<% @user = User.first %>
<p id="notice"><%= notice %></p>
<style>
  a {
    display: block;
  }
  .btn {
    margin-bottom: 15px;
  }

  .btn-group {
   width: 90%;
   margin-left:55px;
  }

  .greeting {
    font-size: 50px !important;
    color: black !important;
  }
</style>
<div class="profile">

<h2 class="greeting">Good afternoon, John!</h2>

<div class="btn-group">
<%= link_to 'Request a ride', req_path, class: 'btn btn-normal' %>
<%= link_to 'How it Works', '#', class: 'btn btn-normal' %>
<%= link_to 'Call us for help', '#', class: 'btn btn-normal' %>
<%= link_to 'Edit your profile', edit_user_path(@user), class: 'btn btn-normal' %>
</div>
</div>

app/views/pages/req.html.erb
<style>
  html {
    color: black !important;
  }
  button {
    padding: 10px;
    font-size: 25px;
  }
  img {
    width: 100%;
    height: auto;
  }
</style>


<h1>WE'RE COMING!</h1>
<img src="https://i1.wp.com/thegeek.life/wp-content/uploads/2015/05/uber-maps.jpg?resize=524%2C400&ssl=1" >

<h1>Other Options</h1>
<ol>
<% @rides.each do |r| %>
<li>
  <h2><%= r['display_name'] %></h2>
  <p><%= r['short_description'] %></p>
  <h4>Cost per minute: $0.<%= r['price_details']['cost_per_minute'] %></h4>
  <button>ACCEPT</button>
</li><br><br>
<% end %>
</ol>

app/views/pages/support.html.erb
<h1>Pages#support</h1>
<p>Find me in app/views/pages/support.html.erb</p>

app/views/riders/_form.html.erb
<%= form_for(@rider) do |f| %>
  <% if @rider.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rider.errors.count, "error") %> prohibited this rider from being saved:</h2>

      <ul>
      <% @rider.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone, "Phone Number" %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email, "Email address" %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <label>Insurance Provider</label><br>
    <%= f.collection_select :ins_provider_id, InsCompany.all, :id, :name, { include_blank: true } %><br>
  </div>
  <div class="field">
    <%= f.label :ins_card_photo, "Add a photo of Insurance Card" %><br>
    <%= f.file_field :ins_card_photo %>
  </div>
  <div class="field">
    <%= f.check_box :tos_agreed %>
    <%= f.label :tos_agreed, 'I agree to the Terms and Conditions of Service' %>
  </div>

  <div class="actions">
    <%= f.submit 'Create Account' %>
  </div>
<% end %>

app/views/riders/edit.html.erb
<h1>Editing Rider</h1>

<%= render 'form' %>

<%= link_to 'Show', @rider %> |
<%= link_to 'Back', riders_path %>

app/views/riders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Riders</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Ins provider</th>
      <th>Tos agreed</th>
      <th>Provider</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @riders.each do |rider| %>
      <tr>
        <td><%= rider.first_name %></td>
        <td><%= rider.last_name %></td>
        <td><%= rider.phone %></td>
        <td><%= rider.email %></td>
        <td><%= rider.ins_provider_id %></td>
        <td><%= rider.tos_agreed %></td>
        <td><%= rider.provider %></td>
        <td><%= link_to 'Show', rider %></td>
        <td><%= link_to 'Edit', edit_rider_path(rider) %></td>
        <td><%= link_to 'Destroy', rider, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rider', new_rider_path %>

app/views/riders/new.html.erb
<%= link_to 'Back', root_path %><br><br>
<h1>Ride with Servo. Live Longer.</h1>

<%= render 'form' %>

app/views/riders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @rider.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @rider.last_name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @rider.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @rider.email %>
</p>

<p>
  <strong>Ins provider:</strong>
  <%= @rider.ins_provider_id %>
</p>

<p>
  <strong>Tos agreed:</strong>
  <%= @rider.tos_agreed %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @rider.provider %>
</p>

<%= link_to 'Edit', edit_rider_path(@rider) %> |
<%= link_to 'Back', riders_path %>

app/views/users/_form.html.erb
<div class="form-panel">
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.email_field :email, placeholder: 'Email', class: 'form-input' %><br>
  <%= f.password_field :password_digest, placeholder: 'Password', class: 'form-input'%>
  <div class="actions">
    <%= f.submit 'Create Account', class: 'btn btn-main form-submit' %>
  </div>
<% end %>
<br><br>
<p class="main-subtext" style="font-size: 31px;">By creating an account you agree to the SERVO <br><%= link_to 'Terms and Conditions of Service', '#' %></p>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>



<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password digest</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= render 'layouts/top_logo' %>

<%= render 'form' %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<style>
  a {
    display: block;
  }
  .btn {
    margin-bottom: 15px;
  }

  .btn-group {
   width: 90%;
   margin-left:55px;
  }
</style>
<div class="profile">
<img src="/images/good_man.jpg" style="border-radius: 50%;" height="300" width="300">

<h2 class="greeting">Good afternoon, John!</h2>

<div class="btn-group">
<%= link_to 'Call for help', edit_user_path(@user), class: 'btn btn-normal' %>
<%= link_to 'Back', users_path, class: 'btn btn-normal' %>
<%= link_to 'Settings', '#', class: 'btn btn-normal' %>
<%= link_to 'FAQs', '#', class: 'btn btn-normal' %>
</div>
</div>